# Generated by Django 5.0.2 on 2024-03-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
