# Generated by Django 5.0.2 on 2024-02-28 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('day', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='myapp.category')),
            ],
        ),
    ]
